# R for travis documentation: https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r: bioc-devel

# Strict checks in place
warnings_are_errors: true

# Run binary install of testthat
r_binary_packages: 
  - testthat

bioc_packages:
  - BiocGenerics
  - S4Vectors
  - GenomicRanges
  - SummarizedExperiment
  - Biobase
  - S4Vectors
  - IRanges
  - BiocStyle

# Test code coverage
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'