language: r
sudo: required

# Strict checks in place
warnings_are_errors: true

# Flag as Bioconductor package
bioc_required: true

# Run binary install of testthat
r_binary_packages: 
  - testthat

bioc_packages:
  - BiocGenerics
  - S4Vectors
  - GenomicRanges
  - SummarizedExperiment
  - Biobase
  - IRanges
  - Homo.sapiens
  - hgu95av2.db
  - GenomicFeatures
  - TxDb.Hsapiens.UCSC.hg19.knownGene
  - hgu133a.db

# Test code coverage
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'library(covr);codecov()'